---
mongo:
  image: mongo:2.6
content:
  build: .
  ports:
  - "9000:8080"
  links:
  - "mongo:mongo"
  environment:
    RACKSPACE_USERNAME:
    RACKSPACE_APIKEY:
    RACKSPACE_REGION: DFW
    CONTENT_CONTAINER: deconst-dev-content
    ASSET_CONTAINER: deconst-dev-assets
    MONGODB_URL: mongodb://mongo:27017/content
    CONTENT_LOG_LEVEL: debug
