---
content:
  build: .
  ports:
  - "80:8080"
  environment:
    RACKSPACE_USERNAME:
    RACKSPACE_APIKEY:
    RACKSPACE_REGION: DFW
    RACKSPACE_CONTAINER: content-service-dev
    CONTENT_LOG_LEVEL: debug
