---
content:
  build: .
  ports:
  - "9000:8080"
  environment:
    RACKSPACE_USERNAME:
    RACKSPACE_APIKEY:
    RACKSPACE_REGION: DFW
    CONTENT_CONTAINER: deconst-dev-content
    ASSET_CONTAINER: deconst-dev-assets
    CONTENT_LOG_LEVEL: debug
