---
mongo:
  image: mongo:2.6
content:
  build: .
  ports:
  - "9000:8080"
  links:
  - "mongo:mongo"
  environment:
    RACKSPACE_USERNAME:
    RACKSPACE_APIKEY:
    RACKSPACE_REGION:
    RACKSPACE_SERVICENET: "false"
    ADMIN_APIKEY:
    CONTENT_CONTAINER:
    ASSET_CONTAINER:
    MONGODB_URL: mongodb://mongo:27017/content
    CONTENT_LOG_LEVEL:
    CONTENT_LOG_COLOR: "true"
    NODE_ENV: development
  volumes:
  - ".:/usr/src/app"
  command: script/dev
