apiVersion: v1
kind: Service
metadata:
  namespace: deconst
  name: content
  labels:
    name: content
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: content
  selector:
    name: content
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: deconst
  name: content
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: content
    spec:
      containers:
        - name: content
          image: $DOCKER_IMAGE
          ports:
            - name: content
              containerPort: 8080
          env:
            - name: ADMIN_APIKEY
              value: \"$ADMIN_APIKEY\"
            - name: ACTION
              value: $ACTION
            - name: INTEGRATION
              value: $INTEGRATION
            - name: NODE_ENV
              value: $NODE_ENV
            - name: STORAGE
              value: $STORAGE
            - name: RACKSPACE_USERNAME
              value: $RACKSPACE_USERNAME
            - name: RACKSPACE_APIKEY
              value: $RACKSPACE_APIKEY
            - name: RACKSPACE_REGION
              value: $RACKSPACE_REGION
            - name: RACKSPACE_SERVICENET
              value: \"$RACKSPACE_SERVICENET\"
            - name: CONTENT_CONTAINER
              value: $CONTENT_CONTAINER
            - name: ASSET_CONTAINER
              value: $ASSET_CONTAINER
            - name: MONGODB_PREFIX
              value: $MONGODB_PREFIX
            - name: MONGODB_URL
              value: $MONGODB_URL
            - name: ELASTICSEARCH_HOST
              value: $ELASTICSEARCH_HOST
            - name: CONTENT_LOG_LEVEL
              value: $CONTENT_LOG_LEVEL
            - name: CONTENT_LOG_COLOR
              value: \"$CONTENT_LOG_COLOR\"
---
apiVersion: v1
kind: Service
metadata:
  namespace: deconst
  name: staging-content
  labels:
    name: staging-content
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: staging-content
  selector:
    name: staging-content
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: deconst
  name: staging-content
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: staging-content
    spec:
      containers:
        - name: staging-content
          image: $DOCKER_IMAGE
          ports:
            - name: staging-content
              containerPort: 8080
          env:
            - name: ADMIN_APIKEY
              value: \"$ADMIN_APIKEY\"
            - name: ACTION
              value: $ACTION
            - name: INTEGRATION
              value: $INTEGRATION
            - name: NODE_ENV
              value: $NODE_ENV
            - name: STORAGE
              value: $STORAGE
            - name: RACKSPACE_USERNAME
              value: $RACKSPACE_USERNAME
            - name: RACKSPACE_APIKEY
              value: $RACKSPACE_APIKEY
            - name: RACKSPACE_REGION
              value: $RACKSPACE_REGION
            - name: RACKSPACE_SERVICENET
              value: \"$RACKSPACE_SERVICENET\"
            - name: CONTENT_CONTAINER
              value: staging-$CONTENT_CONTAINER
            - name: ASSET_CONTAINER
              value: staging-$ASSET_CONTAINER
            - name: MONGODB_PREFIX
              value: staging_
            - name: MONGODB_URL
              value: $MONGODB_URL
            - name: ELASTICSEARCH_HOST
              value: $ELASTICSEARCH_HOST
            - name: CONTENT_LOG_LEVEL
              value: $CONTENT_LOG_LEVEL
            - name: CONTENT_LOG_COLOR
              value: \"$CONTENT_LOG_COLOR\"
            - name: PROXY_UPSTREAM
              value: http://content.deconst.svc.cluster.local:9000/
            - name: STAGING_MODE
              value: \"true\"
